apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app01
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app01
        image: nasi101/netflix:latest
        ports:
        - containerPort: 80
